### ISSUE TITLE
Add sensible default choices and add --assume-default option for automated installers

### ISSUE THREAD

**Issue by axos88** [adafruit/Adafruit-PiTFT-Helper#12]

**Comment by ladyada** [comment]
could be good...send a pull request and we'll take a look, thanks! :)

**Comment by axos88** [comment]
Why are you closing an issue that has not been resolved?

**Comment by ladyada** [comment]
Its not really an issue or problem - its more of a suggestion - and right now we're super busy. if you send a pull request we'll take a look!

**Comment by axos88** [comment]
fair enough
