### ISSUE TITLE
PiTFT-Helper breaks gamecon GPIO module in RetroPie bc of old kernel version

### ISSUE THREAD

**Issue by TefaTBob** [adafruit/Adafruit-PiTFT-Helper#14]
I had the gamecon GPIO controller working perfectly on the newest version of RetroPie on a Rpi3. However when I follow the instructions to install a PiTFT 3.5" screen for emulators, the kernel that the adafruit-pitft-helper installs is RetroPie 4.1.14 v7, where the newest version, that RetroPie fresh installs and that the gamecon GPIO driver works with is 4.4.X-something. (Sorry don't have it running in front me.) I can actually see it uninstalling the gamecon module when I run the pitft-helper scripts, and then can't re-install gamecon from the RetroPie setup util.. Are there any plans to update the kernel here?

**Comment by TefaTBob** [comment]
@brennen Any thoughts on this, plans to use current kernels, or ways that I can manually etc?

**Comment by ladyada** [comment]
fixed with totally new system & guides updated!
