### ISSUE TITLE
Kernel Panic when PiTFT attached to PiZero

### ISSUE THREAD

**Issue by TheQYD** [adafruit/Adafruit-PiTFT-Helper#15]
(TL;DR - When I boot up the PiZero after installing the PiTFT kernel, the kernel panics a few minutes later)

After hardware hacking my 3.5" Resistive Touch PiTFT by removing the header pins and soldering wires from the PiZero to the PiTFT solder pads, I installed NOOBs and turned everything on. I left the PiZero for a solid 10 minutes and then got on to installing the kernel for the PiTFT.

After following the Easy Install directions on adafruit, I rebooted the device only to see a kernel panic on my screen five minutes later. I restarted five more times before formatting the 32GB SD card and reinstalling NOOBs. The same thing happened.

I then switched to another PiZero and PiTFT and tried the same thing -- this time with the header pins on the PiTFT left on and header pins soldered onto the PiZero so they can fit together. The same thing happened.

However, after reinstalling NOOBs and putting it in a Raspberry Pi 3, there was no kernel panic.

What is happening? I thought the PiZero was compatible with the PiTFT. Was I wrong?

**Comment by ladyada** [comment]
hiya, please use the easy install "Ready to go" image in case the kernel install doesnt work

github issues are not the place for tech support, post in the forums

**Comment by TheQYD** [comment]
apologies
