### ISSUE TITLE
PI-TFT Not working on latest Rasbian image.

### ISSUE THREAD

**Issue by Wferr** [adafruit/Adafruit-PiTFT-Helper#17]
Install went smoothly, but on reboot screen stayed with just back light on and no images / console.

**Comment by ladyada** [comment]
use the easy-install image for now, sounds like things changed!

**Comment by rdpascua** [comment]
I'm also having issue as well. I'm using `2017-04-10-raspbian-jessie`.

**Comment by Random1984** [comment]
I've installed it right now the 35r screen and runs brightly. Just cloned this repo and run as root, rebooted and done.
But the calibration of the touchscreen is a mess! Now I have a TFT touchscreen that misses the spot touched. I've to calibrate it, but it works as screen.

**Comment by rdpascua** [comment]
@Random1984 are you using the latest image?

**Comment by Random1984** [comment]
@rdpascua Yes, last raspbian image downloaded literally yesterday _(2017-07-05 version)_, give it a try.

**Comment by rdpascua** [comment]
@Random1984 Can you guide me how did you do it? Any steps that could help everyone

**Comment by Random1984** [comment]
Sure, my friend! It was easy!
I just downloaded the lastest image from raspbian website (July 2017 Desktop version - [Download](http://vx2-downloads.raspberrypi.org/raspbian/images/raspbian-2017-07-05/2017-07-05-raspbian-jessie.zip)).
After creating the SD using dd I booted the Pi and expanded filesystem with raspi-config.
Once rebooted I updated the system with apt-get, cloned this repository using git clone (`git clone https://github.com/adafruit/Adafruit-PiTFT-Helper`).
In the cloned repository I just run the program declaring the type of screen I'm using (3'5" Resistive screen). I said "YES" when it asked if I want to save the new settings.
`adafruit-pitft-helper -t 35r`
After this I only needed to reboot to get the Desktop on the screen, but touchscreen needs to be calibrated.

**Comment by G-Rath** [comment]
@Random1984 I've got my screen mostly working after following your instructions on a fresh install, but my screen doesn't actually show anything after boot?

If I say yes to the console question, I get a console cursor, but other than that nothing. It mirrors the hdmi output right up until the desktop loads, when the hdmi screen shows the desktop but the PiTFT screen just shows black.

Any suggestions on how I should proceed to fix this?

(If I plug HDMI in after booting without it, the hdmi screen shows the desktop at the resolution of the PiTFT, so it seems like it's something like it's not switching ttys or sources correctly after boot?)

**Comment by ladyada** [comment]
please try this no-kernel-needed installer, its beta but seems to be working (we're integrating it to the guide soon)
https://forums.adafruit.com/viewtopic.php?f=47&t=122926&p=629573#p629573

**Comment by G-Rath** [comment]
While that script seems a lot more promising, now after booting my screen just goes straight to the console on tty1 (i.e: directly after boot).

It seems like I have the same issue basselt is having - except I'm not offered any option for HDMI mirror?

I did it on a literally completely fresh install (just finished about 2 minutes ago). 

Would you prefer for me to make an adafruit forum account and this conversation to the forum post?

**Comment by ladyada** [comment]
yah that would be rad - easier to have one thread :) thank u!

**Comment by G-Rath** [comment]
I've made a new post on the thread :)

**Comment by Random1984** [comment]
@ladyada your new script installed everything in place and now my Pi-TFT 3.5" Resistive is running fine and very well calibrated automatically.
Thanks a lot!

**Comment by ladyada** [comment]
fixed & guides updated!
