### ISSUE TITLE
Support for Raspbian Stretch? 

### ISSUE THREAD

**Issue by alc6379** [adafruit/Adafruit-PiTFT-Helper#19]
I noticed that the images on the HOWTO for setting up the PiTFT were just for Jessie. Are there not any images/kernels available for Stretch, aka Debian 9.1? Or are they in the works?

**Comment by ladyada** [comment]
please try this no-kernel-needed installer, its beta but seems to be working (we're integrating it to the guide soon)
https://forums.adafruit.com/viewtopic.php?f=47&t=122926&p=629573#p629573

**Comment by alc6379** [comment]
Thanks-- I'll give it a shot. Do you want me to provide any feedback here, or on the forum?

**Comment by ladyada** [comment]
either's ok (im pretty sure it works)

**Comment by alc6379** [comment]
Awesome, thanks for the response, again. I can confirm-- works pretty well.
