### ISSUE TITLE
add dependencies

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit-PiTFT-Helper#3]
lets also add 'fbi' for ez testing image viewing

**Comment by ladyada** [comment]
and the wiringpi package that is already on apt.adafruit.com 
"sudo apt-get install wiringpi" works fine now, would be good to auto-install

**Comment by brennen** [comment]
Fixed [here](https://github.com/adafruit/Adafruit-Occidentalis/commit/ebe22185dd68864952a822624e0a2c6def155c6f). Deploying to apt repo momentarily.
