### ISSUE TITLE
Have "ask for console access" remove the appropriate section from /boot/cmdline.txt

### ISSUE THREAD

**Issue by technomalogical** [adafruit/Adafruit-PiTFT-Helper#4]
I dug around in the code and found the line that it edits, but it would be nice if, once you use the tool to enable console access to the PiTFT, you could also remove it (and revert back to HDMI). Currently when you are asked "y/n", choosing "n" just skips the section rather than checking to see if it's present and removing it.

**Comment by brennen** [comment]
Yeah, fair point. Lemme see what I can do.

**Comment by brennen** [comment]
Should be handled now; deploying this version to apt repository shortly.
