### ISSUE TITLE
Error w/2.2" HAT (w/fix)

### ISSUE THREAD

**Issue by PaintYourDragon** [adafruit/Adafruit-PiTFT-Helper#5]
sudo adafruit-pitft-helper -t 22
Fails with message: "[PITFT] Exiting due to error: Unable to update /etc/modules"
Fixable in update_etcmodules(), line 227 -- change "return" to "return 0"

**Comment by brennen** [comment]
D'oh - thanks! Fix inbound.

**Comment by brennen** [comment]
Fix deploys to apt.adafruit.com shortly. Thanks again.
