### ISSUE TITLE
PiTFT 28c console works, startx = blank screen, HDMI output ok

### ISSUE THREAD

**Issue by giantmolecules** [adafruit/Adafruit-PiTFT-Helper#6]
I have two identical Raspberry Pi 2 Setups, both with the latest noobs distro and PiTFT capactitive touchscreens. I followed the instructions here for setting up adafruit-pitft-helper, and the first one worked fine. The second one, following all the same steps as the first, won't display the desktop if I startx from the console. (i do have console enabled on both machines). All I see on this one is a black screen with a short white line. Any suggestions

**Comment by brennen** [comment]
As a first sanity check, can you see what the value of `FRAMEBUFFER` on the second Pi is? `echo $FRAMEBUFFER` should get this.

Or, actually, howsabout just a dump of everything you get by running `env` if you can.

You might also check if `/usr/share/X11/xorg.conf.d/99-fbturbo.conf` has been moved aside (the script should just have moved it to `/home/pi`).

**Comment by giantmolecules** [comment]
ok, on Pi1, echo $FRAMEBUFFER gives me /dev/fb1. on Pi2, nothing is echoed. 99-fbturbo.conf is located in /home/pi on both Pi's

**Comment by brennen** [comment]
Ok, so have a look in `/home/pi/.profile` (or `/home/[YOUR USERNAME HERE/.profile`, really), and see if you've got:

```
export FRAMEBUFFER=/dev/fb1
```

If not, add it and see what happens. If so, maybe `.profile` isn't getting executed. You could throw that line in `.bashrc` instead and see what happens...

**Comment by giantmolecules** [comment]
lovely! Pi2 did not have export FRAMEBUFFER=/dev/fb1 at the end of .profile like Pi1. Now both work! Thanks very much for your help and patience! BTW, these were both fresh installs, nothing other was done to them other than adding the adafruit repository and installing adafruit-pitft-helper...

**Comment by brennen** [comment]
> Thanks very much for your help and patience!

Any time!  Glad that was an easy fix. It does seem like occasionally the helper script is failing there for some reason; I'll add an extra check-and-warning for the presence of that line.
