### ISSUE TITLE
no way to remove on/off button option

### ISSUE THREAD

**Issue by joemijin** [adafruit/Adafruit-PiTFT-Helper#8]
Would you like GPIO #23 to act as a on/off button?

This section only installs the on/off button, selecting "No" doesn't remove it at a later date.

This is a bit painful if you don't know the internals and then take off your PiTFT and replace it with for example an led board which uses GPIO23. What happens then is as soon as the led is activated the Pi turns off. 

I had to blacklist the module to stop it.

**Comment by ladyada** [comment]
gpio on/off is removed so closing :/
